name: Auditoría de dependencias

permissions:
  actions: read
  contents: read

on:
  push:
    branches:
      - main
      - versionAstro
  pull_request:
    branches:
      - main
      - versionAstro

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Restaurar aprobaciones de build (si existe)
        run: |
          if [ -f .github/approved-builds.json ]; then
            mkdir -p ~/.pnpm
            cp .github/approved-builds.json ~/.pnpm/approved-builds.json
            echo "✅ approved-builds.json restaurado en ~/.pnpm/approved-builds.json"
          else
            echo "ℹ️ approved-builds.json no encontrado, se continuará sin aprobaciones preconfiguradas"
          fi
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Setup pnpm
        run: npm install -g pnpm
      - name: Instalar dependencias
        run: pnpm ci
      - name: Ejecutar auditoría de seguridad y mostrar ayuda si falla
        run: |
          pnpm audit --audit-level=moderate || {
            echo "❌ Se detectaron vulnerabilidades en las dependencias.";
            echo "Por favor, revise el reporte de pnpm audit en el log de este workflow.";
            echo "Para corregir los problemas, ejecute en su entorno local:";
            echo "  pnpm audit";
            echo "y siga las recomendaciones para actualizar, eliminar o modificar las dependencias afectadas.";
            echo "Si necesita ayuda, consulte la documentación oficial de pnpm o abra un issue en el repositorio.";
            exit 1;
          }
